### PR TITLE
General improvements to code

### PR DESCRIPTION
**Pull request by ElectronicallyE**
Based upon suggestion made here:
https://github.com/nikisalli/esp32-minecraft-server/issues/3#issuecomment-1933984749

Adjustments made include:
Fixed compiling issues in platformio.ini.
Added WiFi reconnection code.
Set default gamemode to creative.
Added a favicon.
Changed max players to 5.
Deleted the docs directory, which is a duplicate of other code and is not functional.

### CODE REVIEW

**Comment by ElectronicallyE** [comment]
The reasoning for changing platformio.ini can be found here:
https://community.platformio.org/t/pio-stopped-working-and-cannot-complie/36236/2

**Comment by nikisalli** [comment]
hello, does this work without extending the packet buffer?

**Comment by ElectronicallyE** [comment]
I tried extending the buffer and it worked for a large favicon over 6000
byes. I did leave it as is in the pull request as it was not necessary for
the size of the favicon I ended up using.

**Comment by nikisalli** [comment]
ok looks good to me

**Pull request merged**
